# -*- coding: utf-8 -*-
"""resizeImage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qDQVQ3eWyRUkjgEI_hJ_NiH2zkft1MPc
"""

import cv2
import os
from matplotlib import pyplot as plt

# Đường dẫn đến thư mục chứa ảnh
for i in range(10):
  print(i)
  folder_path = '/content/drive/MyDrive/data/val/class_{}'.format(i)

  # Độ rộng và chiều cao mới cho ảnh sau khi resize
  new_width = 28
  new_height = 28

  # Đọc tất cả các tệp tin trong thư mục
  for filename in os.listdir(folder_path):
      # Kiểm tra xem tệp có phải là tệp hình ảnh không (có thể thêm các điều kiện kiểm tra đuôi tệp)
      if filename.endswith(('.png', '.jpg', '.jpeg')):
          # Đường dẫn đầy đủ đến ảnh
          image_path = os.path.join(folder_path, filename)

          # Đọc ảnh từ đường dẫn
          image = cv2.imread(image_path)

          # Resize ảnh
          resized_image = cv2.resize(image, (new_width, new_height))

          # Hiển thị ảnh bằng matplotlib
          # plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
          # plt.show()

          # Lưu ảnh sau khi resize (tùy chọn)
          resized_image_path = os.path.join('/content/drive/MyDrive/data/val/class_{}'.format(i), filename)
          cv2.imwrite(resized_image_path, resized_image)
      print(filename)

image = cv2.imread('/content/drive/MyDrive/data/val/class_9/class_9_30.jpg')
height, width = image.shape[:2]

# In chiều rộng và chiều cao
print("Chiều rộng của ảnh:", width)
print("Chiều cao của ảnh:", height)

start_letter = 'A'
end_letter = 'Z'
for letter_code in range(ord(start_letter), ord(end_letter) + 1):
    letter = chr(letter_code)
    print(letter)

import cv2
import os
from matplotlib import pyplot as plt

# Đường dẫn đến thư mục chứa ảnh
start_letter = 'A'
end_letter = 'Z'

for letter_code in range(ord(start_letter), ord(end_letter) + 1):
    letter = chr(letter_code)
    print(letter)
    folder_path = '/content/drive/MyDrive/data/val/class_{}'.format(letter)

    # Độ rộng và chiều cao mới cho ảnh sau khi resize
    new_width = 28
    new_height = 28

    try:
        # Đọc tất cả các tệp tin trong thư mục
        for filename in os.listdir(folder_path):
            # Kiểm tra xem tệp có phải là tệp hình ảnh không (có thể thêm các điều kiện kiểm tra đuôi tệp)
            if filename.endswith(('.png', '.jpg', '.jpeg')):
                # Đường dẫn đầy đủ đến ảnh
                image_path = os.path.join(folder_path, filename)

                # Đọc ảnh từ đường dẫn
                image = cv2.imread(image_path)

                # Resize ảnh
                resized_image = cv2.resize(image, (new_width, new_height))

                # Hiển thị ảnh bằng matplotlib
                # plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
                # plt.show()

                # Lưu ảnh sau khi resize (tùy chọn)
                resized_image_path = os.path.join('/content/drive/MyDrive/data/val/class_{}'.format(letter), filename)
                cv2.imwrite(resized_image_path, resized_image)
            print(filename)
    except FileNotFoundError:
        print(f"Folder not found: {folder_path}. Skipping...")
        continue

